project_id = "mjbvpwaaeatocglvuuaf"

[functions.analyze-docs]
verify_jwt = false

[functions.enhanced-doc-processing]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.process-documents]
verify_jwt = false
